version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: transaction_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: transactions
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile 
    container_name: transaction_app
    restart: always
    depends_on:
      - postgres
    environment:
      CONFIG_FILE_PATH: "config/config.local.yml"
    ports:
      - "8080:8080"

volumes:
  pgdata: