postgres:
  pool:
    ConnConfig:
      Host: localhost
      Port: 5432
      Database: transactions
      User: postgres
      Password: changeme
      ConnectTimeout: 15 # число секунд

    MaxConnLifetime: 10s
    MaxConnLifetimeJitter: 0s
    MaxConnIdleTime: 5s
    MaxConns: 10
    MinConns: 5
    HealthCheckPeriod: 5s
  Schema: "transaction_test"
  ConnectRetries: 5
  ConnectRetryDelay: 5s

migrations:
  driver: "custom-file-sprintf" # кастомный драйвер, подробности в документации
  directory: "./migrations" # папка с миграциями

seeding: # относиться к пункту - при вервом запуске создать 10 кошельков. Подробнее в документации
  wallets:
    Enabled: true
    FailOnError: false # завершать ли работу при ошибки создания кошелька
    Count: 10
    Balance: 100
    MarkerFile: "./.wallets_seeded"

server:
  host: 0.0.0.0
  port: 8080

logger:
  logger:
    Level: "debug"
    Development: true
    Encoding: "json"
    OutputPaths: ["stdout"]
    ErrorOutputPaths: ["stderr"]
    EncoderConfig:
      MessageKey: "message"
      LevelKey: "level"
      TimeKey: "timestamp"